### PR TITLE
Bring package up to date

### PR DESCRIPTION
**Pull request by VLucet**

### CODE REVIEW

**Comment by gavinsimpson** [comment]
@VLucet Sorry I didn't get to meet you last week and glad to have your help working on MRFtools.

Can we keep the tests and pkgdown actions? We will want tests (ideally as we develop the package from now on - what's there now is basically the results of a few hours of coding over a couple of days quite some years ago now) and having the pkgdown site for the package is useful both as we develop documentation but also for people trying to use the package while it is development.

**Comment by VLucet** [comment]
Hi @gavinsimpson! No problem, I was not at ESA. For the moment, @eric-pedersen has asked me to make sure the package is ready for further dev.

And yes of course, I don't mind adding the actions back!

**Comment by eric-pedersen** [comment]
Thanks for doing this, Val! Gavin, Val's my lab software developer (if only for the next week 😢) and he's interested in using MRFtools in our sspm package (https://github.com/pedersen-fisheries-lab/sspm), so I invited him to join the team.

**Comment by VLucet** [comment]
@eric-pedersen the last thing before I merge is to allow github pages on this repo. I can do it if you give me admin rights, or you can do it in your settings.

**Pull request merged**
